services:
  - type: web
    name: runo-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node --loader tsx/esm src/index.ts
    healthCheckPath: /healthz
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
